# Travis CI (MIT License) configuration file for http://connor-baer.github.io/autumn.
# @link https://travis-ci.org/

# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/ruby/
language: ruby

# Declare versions of Ruby to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  fast_finish: true

  include:
    - rvm: '2.3.1'
      gemfile: gemfile
      env: LINT=1
    - rvm: 'ruby-head'
      gemfile: gemfile

  allow_failures:
    - rvm: 'ruby-head'

before_install:
  - nvm install node

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  # Install JavaScript dependencies.
  - if [[ "$LINT" == "1" ]]; then yarn; fi

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  #!/usr/bin/env bash

  # Build the website.
  - bundle exec jekyll build
  # Lint the JavaScript code.
  - if [[ "$LINT" == "1" ]]; then yarn lint; fi

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email:
    email:
      - admin@connorbaer.co

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
